name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test_asdf_0_16:
    name: plugin test (asdf >= 0.16)
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - run: sudo apt-get install autoconf pkg-config help2man libconfuse-dev libarchive-dev
        if: matrix.os == 'ubuntu-latest'
      - run: brew install confuse libarchive pkg-config automake
        if: matrix.os == 'macos-latest'
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@b7bcd026f18772e44fe1026d729e1611cc435d47
        with:
          command: fwup --version
  plugin_test_asdf_0_15:
    name: plugin test (asdf < 0.16)
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - run: sudo apt-get install autoconf pkg-config help2man libconfuse-dev libarchive-dev
        if: matrix.os == 'ubuntu-latest'
      - run: brew install confuse libarchive pkg-config automake
        if: matrix.os == 'macos-latest'
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v4
        with:
          asdf_branch: v0.15.0
          version: 1.12.0
          command: fwup --version
